// src/app/about/page.jsx (or wherever your AboutUs component is located)
"use client";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";

export async function generatemetadata() {
  return {
    title: "About Us",
    description: "Generated by create REDVision Technologies.",
  };
}

export default async function AboutUs() {
  return (
    <div className="">
      {/* Hero Section */}
      <div className="flex bg-center bg-no-repeat bg-cover bg-[url('/images/pay-premium/pay-premium.webp')] overflow-hidden text-start justify-start items-center h-64">
        <div className="max-w-screen-xl mx-auto">
          <h1 className="text-gray-900 text-3xl md:text-5xl font-bold">
            Welcome to Ethicus Wealth Services
          </h1>
        </div>
      </div>

      {/* Introduction Section */}
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, delay: 0.2 }}
        className="md:my-20 my-10 md:px-0 px-3"
      >
        <h2 className="text-4xl text-[var(--rv-primary)] md:text-5xl font-bold mb-6 text-center">
          About Us
        </h2>
        <p className="text-gray-800 max-w-5xl mx-auto text-center mb-5">
          Ethicus Wealth Pvt. Ltd. is a Wealth Management/Financial Planning
          Firm. This Firm running by professionals and Experience Management.
          Our Expertise is in "Need Base Financial Planning" which helps our
          customers to achieve their Financial Goals with proper Risk
          Management.
        </p>

        {/* Top Features Section */}
        <h3 className="text-3xl text-center font-semibold text-[var(--rv-primary)] mb-6">
          Our Top Features
        </h3>
        <div className="grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-6 max-w-6xl mx-auto px-4">
          {[
            "250+ Crore AUM",
            "Serving 1500+ Clients",
            "20+ Qualified Team Members",
            "Cutting Edge Technology",
            "30+ Years Combined Experience",
            "35+ Research Tools",
          ].map((feature, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-md p-6 text-center hover:shadow-lg transition duration-300"
            >
              <p className="text-lg font-medium text-gray-800">{feature}</p>
            </div>
          ))}
        </div>
      </motion.section>

      <div className="bg-[var(--rv-secondary)]">
        <div className="max-w-screen-xl mx-auto md:py-20 py-10 md:px-0 px-3">
          {/* Transforming Ambitions Section */}
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-6 items-center"
          >
            <div className="relative">
              <Image
                src="/images/aboutus/aboutus.webp"
                alt="About Us"
                width={550}
                height={550}
                className="rounded-xl grayscale shadow-lg"
              />
            </div>
            <div>
              <h2 className="text-3xl text-[var(--rv-primary)] md:text-4xl font-bold mb-6">
                How We Define "Ethicus"
              </h2>
              <p className=" text-gray-100 mb-6">
                The name 'Ethicus" is derived from the Greek word "ethos", which
                refers to character, moral nature, or guiding beliefs. The
                suffix "-icus" suggests a relation to or association with, often
                used in academic or formal contexts. Together, "Ethicus conveys
                a sense of ethical principles and integrity, aligning well with
                the concept of wealth management, where trust and moral
                responsibility are paramount. This name implies a commitment to
                managing wealth in a way that is not only profitable but also
                aligned with ethical standards and values.
              </p>
            </div>
          </motion.section>
        </div>
      </div>

      <div className="max-w-screen-xl mx-auto md:py-20 py-10 md:px-0 px-3">
        {/* Mission, Vision, Value Section */}
        <motion.section
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.6 }}
          className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16"
        >
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            {/* <Image
              src="/svg/mission.svg"
              alt="Mission"
              width={60}
              height={60}
            /> */}
            <h3 className="text-2xl font-bold text-white my-3">Our Mission</h3>
            <p className="text-gray-100">
              We aspire to be known as "Wealth Creators & Financial Planners,
              driven by commitment and Core Values.
            </p>
          </div>
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            {/* <Image src="/svg/vision.svg" alt="Vision" width={60} height={60} /> */}
            <h3 className="text-2xl font-bold text-white my-3">Our Vision</h3>
            <p className="text-gray-100">
              To Educate and Empower the investors to make better investment
              decisions through, Quality Advice, Innovative Products, Superior
              Services.
            </p>
          </div>
        </motion.section>

        {/* Core Values */}
        <motion.section
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.6 }}
          className="mb-16 "
        >
          <h3 className="text-3xl  font-semibold text-[var(--rv-primary)] text-center mb-6">
            Core Values
          </h3>
          <p className="text-center max-w-3xl mx-auto text-gray-700 mb-4">
            We firmly believe that our Core Values have served as the
            Cornerstone for the Expansion and Success of our Company.
          </p>
          <ul className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 text-center max-w-4xl mx-auto">
            {[
              "Financial Education",
              "Commitment",
              "Speed",
              "Transparency",
              "Client Centric Approach",
            ].map((value, i) => (
              <li
                key={i}
                className="bg-gray-100 p-4 rounded-lg shadow text-[var(--rv-primary)] font-semibold"
              >
                {value}
              </li>
            ))}
          </ul>
        </motion.section>
      </div>

      <div className="bg-[var(--rv-secondary)]">
        <div className="max-w-screen-xl mx-auto md:py-20 py-10 md:px-0 px-3">
          <motion.section
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.8 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-4xl lg:text-5xl font-bold text-white mb-12 text-center">
              Meet the Minds Powering the Future of Wealth Management
            </h2>
            <div className="mb-12">
              <div className="group bg-[var(--rv-primary)] p-8 rounded-xl shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl mb-10">
                <div className="grid md:grid-cols-6 justify-center gap-5">
                  <div className="md:col-span-2">
                    <Image
                      src="/images/founder1.jpg"
                      alt="Mr. ABHISHEK SHAH"
                      width={380}
                      height={380}
                      className="rounded grayscale group-hover:grayscale-0 transition-all mr-4"
                    />
                  </div>
                  <div className="md:col-span-4">
                    <div>
                      <h3 className="text-2xl font-bold text-white pt-0 mt-0 mb-4">
                        Mr. ABHISHEK SHAH
                      </h3>
                    </div>
                    <p className="text-gray-100 mb-4">
                      Abhishek is a Financial Freedom Coach, a Keynote
                      Speaker/Educator, an Author. Abhishek is also the Founder
                      of Ethicus Wealth
                    </p>
                    <p className="text-gray-100 mb-4">
                      (www.ethicuswealth.com)/Ethicus Academy - Financial
                      Planning & Wealth Advisory Firm. He has over 22 years+
                      Experience in the Financial Services Industry. He is
                      passionate about helping people to understand the concept
                      of financial freedom, wealth creation and preservation of
                      wealth.
                    </p>
                    <p className="text-gray-100 mb-4">
                      He has established Ethicus Wealth with the aim of helping
                      individual and corporate clients to make informed and
                      correct investment decisions. After that, he ventured into
                      various financial products like Mutual Funds, Life
                      Insurance, Health Insurance, General Insurance, NPS, FD,
                      Bonds, Equity, PMS, AIF, and currently serving 1500+ happy
                      & wealthy clients.
                    </p>
                    <p className="text-gray-100 mb-4">
                      His passion lies in educating and enlightening people
                      about the importance of effective wealth management and he
                      firmly believes in creating and nurturing wealthy habits
                      in his Investors, which transformed many ordinary
                      Investors into successful Investors.
                    </p>

                    {/* Quick Bio */}
                    <div className="mt-6">
                      <h4 className="text-xl font-semibold text-white mb-2">
                        Quick Bio
                      </h4>
                      <ul className="list-disc pl-5 space-y-2 text-gray-100">
                        <li>
                          CFP (FPSB - Financial Planning Standard Board, USA)
                        </li>
                        <li>
                          CFGP (AAFM - American Academy of Financial Management)
                        </li>
                        <li>
                          30+ Certification courses related to Financial Markets
                          (BSE, NSE, AMFI, etc.)
                        </li>
                        <li>B.Com (South Gujarat University)</li>
                        <li>
                          Author of the book <em>"Mera Wealth Plan"</em>
                        </li>
                        <li>
                          Regular article writer on financial topics in
                          Divyabhaskar, Gujarat Samachar, and Gujarat Guardian
                          newspapers
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="group bg-[var(--rv-primary)] p-8 rounded-xl shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl">
                <div className="grid md:grid-cols-6 justify-center md:gap-5">
                <div className="md:col-span-4 mb-4">
                    <div>
                      <h3 className="text-2xl font-bold text-white pt-0 mt-0 mb-4">
                      Ms. RUBINA HAKIM (CFGP)
                      </h3>
                    </div>
                    <p className="text-gray-100 mb-4">
                    Rubina is a Director & BDO of Ethicus Wealth. She is passionate about helping
people for FINANCIAL PLANNING & WEALTH MANAGEMENT through Various
Wealth Management products.
                    </p>
                    <p className="text-gray-100 mb-4">
                    She does research & analysis of Mutual Funds. Currently she is educating
people on how to achieve their Financial Goals through Financial Planning. Her
motive is to give correct investment advice related to their risk appetite and
protect their families against uncertainties and helping them to achieve their
Financial Goals in a discipline manner.
                    </p>

                    {/* Quick Bio */}
                    <div className="mt-6">
                      <h4 className="text-xl font-semibold text-white mb-2">
                        Quick Bio
                      </h4>
                      <ul className="list-disc pl-5 space-y-2 text-gray-100">
                        <li>
                        CFGP (AAFM - American Academy of Financial Management)
                        </li>
                        <li>
                        AMFI Certified - NISM
                        </li>
                        <li>
                        IRDA Certified - NISM
                        </li>
                        <li>Equity Fundamental and Technical Analysis</li>
                        <li>
                        Diploma In Information Technology (Gujarat Technological University)
                        </li>
                        <li>
                          Regular article writer on financial topics in
                          Divyabhaskar, Gujarat Samachar, and Gujarat Guardian
                          newspapers
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div className="md:col-span-2 col-span-4">
                    <Image
                      src="/images/founder2.webp" // Replace with actual image path
                      alt="Nakul jain"
                      width={300}
                      height={80}
                      className="rounded grayscale group-hover:grayscale-0 transition-all mr-4 "
                    />
                  </div>
                </div>
              </div>
            </div>
          </motion.section>
        </div>
      </div>

      <div className="max-w-screen-xl mx-auto py-20">
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 1 }}
          className="text-center"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Join Us on a Journey to Infinite Growth!
          </h2>
          <p className=" text-gray-700 max-w-3xl mx-auto mb-8">
            At Ethicus Wealth Pvt Ltd, we don’t just manage wealth—we shape
            financial futures. Join us in transforming financial growth for
            business owners across India. Together, we’ll redefine what’s
            possible.
          </p>
          <Link href="/contact-us">
            <Button className="bg-[var(--rv-secondary)] hover:bg-[var(--rv-primary)] px-6 py-3 rounded-full ">
              Get Started
            </Button>
          </Link>
        </motion.section>
      </div>
    </div>
  );
}
